name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Runs on macOS checks

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Install Docker
          run: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            docker --version  # Verify Docker installation
  
        - name: Start Docker Service (If Needed)
          run: |
            sudo systemctl start docker
            sudo systemctl enable docker
  
        - name: Build Docker Image
          run: docker build -t my-app .