name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Runs on macOS checks

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: List Directory (Debugging)
          run: ls -l  # Check if Dockerfile is present
  
        - name: Build Docker Image
          run: docker build -t my-app .