name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Runs on macOS check

    steps:
      - name: Build Docker Image
        run: |
          brew install --cask docker 
          docker build -t my-app:latest .
      
      - name: List Docker Images
        run: docker images