name: Build and Push Docker Image on macOS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker on macOS
        run: |
          brew install --cask docker
          open -a docker
          sleep 15  # Wait for Docker to start
      - name: Build docker Image
        run: docker build -t my-app . 