name: Build and Push Docker Image on macOS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with AWS ECR
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker Image
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 061051251198.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker Image to AWS ECR
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          docker push 061051251198.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
